package constant

const (
	HTTP_METHOD_GET  = "GET"
	HTTP_METHOD_POST = "POST"

	PAGINATION_LIMIT_SIZE_DEFAULT = 10
	PAGINATION_TYPE_DEFAULT       = "DEFAULT"
	PAGINATION_TYPE_AFTER         = "AFTER"
	PAGINATION_TYPE_BEFORE        = "BEFORE"

	TIME_LAYOUT = "2006-01-02 15:04:05"
	TIMEZONE    = "Asia/Jakarta"
)
